sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 101.33.215.232
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: 101.33.215.232
    port: 6379
    database: 0